version: '2.1'
services:
  postgres:
    container_name: djb_postgres
    image: postgres:9.6.1
    restart: always
    env_file: ./.env
    ports:
      - '5432'

  django:
    container_name: djb_django
    build: ./django
    restart: always
    expose:
      - '8000'
    depends_on:
      - postgres
    volumes:
      - ./django:/srv/djb_django
    env_file: ./.env
    command: /usr/local/bin/gunicorn main.wsgi:application -w 2 -b :8000

  nginx:
    container_name: djb_nginx
    build: ./nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/try_files:/www/data
      - ./django/static:/var/www/static
